Repository kenny95h/TraineeTrackerTestFramework, pull requests merged in 2022-08, with the labels that each got.

#6 Initial POM Pages
  TraineeTrackerFramework/TraineeTrackerFramework/lib/TT_Website.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Account/TT_AccessDenied.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Account/TT_LoginPage.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Admin/TT_Index.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Create.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Delete.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Details.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Edit.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Index.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/TT_Privacy.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_Create.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_Delete.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_Details.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_Edit.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_Index.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_View_Trainer.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Create.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Delete.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Details.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Edit.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Index.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainers/TT_Error.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainers/TT_Index.cs
Labels: enhancement

#11 add find elements for login page and start index page
  TraineeTrackerFramework/TraineeTrackerFramework/AppConfigReader.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Account/TT_LoginPage.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Admin/TT_Index.cs
Labels: enhancement

#7 Extra Web Elements
  TraineeTrackerFramework/TraineeTrackerFramework/Program.cs
  TraineeTrackerFramework/TraineeTrackerFramework/TraineeTrackerFramework.csproj
  TraineeTrackerFramework/TraineeTrackerFramework/lib/TT_Website.cs
Labels: enhancement

#13 Dylan pom pages
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Account/TT_AccessDenied.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Create.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainers/TT_Error.cs
Labels: enhancement

#20 Added trainee create, tracker index+view
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_Index.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_View_Trainer.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Create.cs
Labels: enhancement

#23 Added Ids to ViewTrainer in Trackers
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_View_Trainer.cs
Labels: enhancement

#24 AppConfigReader and POMs
  TraineeTrackerFramework/TraineeTrackerFramework/AppConfigReader.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Account/TT_LoginPage.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Delete.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Details.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Edit.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Index.cs
Labels: enhancement

#28 updated index page for trainers
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainers/TT_Index.cs
Labels: enhancement

#32 Jon pom pages
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Delete.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Details.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Edit.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Courses/TT_Index.cs
Labels: enhancement

#30 Fixing TT_Login.cs IDs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Account/TT_LoginPage.cs
Labels: enhancement

#37 updated view trainer in trackers
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_View_Trainer.cs
Labels: enhancement

#35 Added more IDs to Tracker POMs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_Details.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trackers/TT_Edit.cs
Labels: bug

#38 Made a slight edit to Index.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Admin/TT_Index.cs
Labels: bug

#39 Added "logo_id" and "privacy_link" to replace XPaths
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Delete.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Details.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Edit.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Index.cs
Labels: bug

#43 Creation of files using Scenario 6.1.1
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/TraineesDetails.feature
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/TraineesDetails.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/TraineesDetailsStepDefinitions.cs
Labels: enhancement

#44 Ellis
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/ViewTrainersDetails.feature
Labels: enhancement

#49 Dan index feature files
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/Courses_Index.feature
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/Courses_Index.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/Trainees_Index.feature
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/Trainees_Index.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/Trainers_Index.feature
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/Trainers_Index.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/Courses_IndexStepDefinitions.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/Trainees_IndexStepDefinitions.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/Trainers_IndexStepDefinitions.cs
Labels: enhancement

#45 Editing a line in EditTrainee Gherking Script so that everything has an degree of consistency
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/EditTrainee.feature
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/EditTrainee.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/EditTraineeStepDefinitions.cs
  TraineeTrackerFramework/TraineeTrackerFramework/TraineeTrackerFramework.csproj
Labels: enhancement

#52 Changed 2 "WebDriver" variables to "IWebDriver"
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Edit.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainees/TT_Index.cs
Labels: enhancement

#53 Jon tt website add page references
  TraineeTrackerFramework/TraineeTrackerFramework/lib/TT_Website.cs
Labels: enhancement

#65 Maks login step definitions
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/Login.feature
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/Login.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/LoginStepDefinitions.cs
  TraineeTrackerFramework/TraineeTrackerFramework/TraineeTrackerFramework.csproj
Labels: enhancement

#72 Update to README
  README.md
Labels: enhancement

#73 README update
  README.md
Labels: documentation

#74 Update README.md
  README.md
Labels: documentation

#75 Update README.md
  README.md
Labels: documentation

#78 Update README.md
  README.md
Labels: documentation

#77 Update README.md
  README.md
Labels: documentation

#79 README update
  README.md
Labels: documentation

#80 Update README.md
  README.md
Labels: documentation

#82 Automated Index Page Tests (Courses, Trainees and Trainers)
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/Courses_IndexStepDefinitions.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/Trainees_IndexStepDefinitions.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/Trainers_IndexStepDefinitions.cs
Labels: enhancement

#84 Jon view trainee details
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/TraineesDetails.feature
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/TraineesDetails.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/ViewTrainersDetails.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/TraineesDetailsStepDefinitions.cs
  TraineeTrackerFramework/TraineeTrackerFramework/lib/pages/Trainers/TT_Index.cs
Labels: enhancement

#86 Update README.md
  README.md
Labels: documentation

#90 Maks readme update
  README.md
Labels: documentation

#96 Jon trainee tracker
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/TraineesDetails.feature
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Features/TraineesDetails.feature.cs
  TraineeTrackerFramework/TraineeTrackerFramework/BDD/Steps/TraineesDetailsStepDefinitions.cs
Labels: bug

#101 Update README.md
  README.md
Labels: documentation

#102 Update README.md
  README.md
Labels: documentation
